#cloud-config

# |- Set timezone
timezone: Europe/Berlin

# |- Update /etc/hosts
manage_etc_hosts: true

# |- Update hostname and fqdn
hostname: ${HOST_NAME}

# |-Update apt database on first boot | Default: true
#apt_update: true
package_update: true

# |- Upgrade the instance on first boot | Default: false
#apt_upgrade: true
package_upgrade: false

# |- Install additional packages on first boot | Default: non
packages:
    - curl
    - unzip
    - rsync

# |- Configure users and groups
users:
  - default
  - name: ${USERNAME}
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkWco4WiGFw9/q9I6EWLyX58o0g9h4GaIA0unAqktMgybU4bWmZ/59LynImJtbxK46kprLE/lcew7jpX2p9iS+WKro13NmlfxzRXCXufMu8zuuR8od+dcBCagHypVo7r00/4seakdc6i/DCPDAl8RcBMsR15ZWa+pwQiHFIHUnBXOaBGH8v/UuLhcw7IzdXi2juhIQ8vrn3XFYGtmACnE+/lweE5bys/ynqp+ezINUmaqtpAGaJqNT5Skwy9DelbUkxOuvliIC2vBMj7Hjb8XGUSbgFKznCEsMwKkdEDgg5pAHFwJRAN7EQ6IPg7pMloNs4GzqtWGfV3Wa9ZXgCl+RCZ7AN7Ng0mVdOhtwkxh5oa3T+U7JNhWEMmvKt4iK2t1sk+upl3lS12CXcQd8YIPuwjZ9kpYdrDQtPkKgZLWKP5gbRwwMc8Qh5TP4jePo8s0M8qff0E/vC2fNaWNAEis5Bk43skG72T4jpveqLRONNV5l3URb92XJNJaTItrVW6xFzcG2XPVSqyHFeNKT0wBmalfbDQ0llZoTbL9VOua4aXd3KJc23XsPN12e1iK8n5tBB2IiZAF4aNzhyGo3jngB9nsjHL/HrlZ9RuBA96YOFWUtnemaIDGphJuTJ3tclfD9uL9h5r8nQiwrSssumV/p/5ZtWvoxJvFN9OTOs9K0Jw==
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDuPRw4hGeZAogqVNo+xVgJLQpEr3TIl824K1BZBLaRtk3Pcn4punT5NDnXMp2fDHlq4AtMYSl+Rby9uU43MTFzIhmU2rBFtis+iu/UiUGocnGXWipyH31Pg7vt2hFGU5Gl/StrCl/uXk8hkHoSqMHlZUZCek18c2wXA3cz640mCtG1fEnInZ7nvCIBNdI0Rc2bcIaJiNGW7RiEsRK2jYNnl0TwabjEwrCgJdtSP1VsTI0KPU9DFKw4TCavwhBtfOXAI7rGRXeJnK93aEMJJlSKWYiPh7BWxOELumU20CflP+odReZj2SXDwGYXkYbUq5nZg3xY8THLHlvS60HUtJL8xdl5wq9ZPb8BxXFXqhSy3Ps9IsgbzCDReCXe/8kBz3fWY8KxDKF9g844pIcMTEkBj4E1QYFH7DKvMJyCFiqOHZqXawUdCBMX9SToLghJ0CDReC1qoKrq3jAqjjG/GR5W+03IrDhvZneVhHRryowQcqlbJU7LVuGjTA27XP/CJpqLSc2lC76gmogDCBb8lLmBfxr6G0Jg80Im486Vlgccb0ZSoFrgje7Fb62JUyrZI8BnantBe3aV1UIvRxtmDiiHrNsHFhsRnT2BFcsUHREbwnD89qNClZDqJ9Z9kALqYJb6qyAZQOdZdY/AySL50Q0wmAsLnZKswkiglslvJ5qg/Q==
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo, adm, docker
    shell: /bin/bash

# |- Run arbitrary commands. Each item can be either a list or a string. All commands must be proper yaml
runcmd:
  - chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers ${USERNAME}' /etc/ssh/sshd_config
  - restart ssh
  - [ wget, "https://raw.githubusercontent.com/tankibaj/dotfiles-ubuntu/main/install.sh", -O, /home/${USERNAME}/dotfiles.sh ]
  - chmod +x /home/${USERNAME}/dotfiles.sh
  - sh -c "$(curl -fsSL https://get.docker.com)"
  - export DOCKER_PATH=/usr/local/lib/docker/cli-plugins
  - sudo mkdir -p $DOCKER_PATH
  - export GET_LATEST_DOCKER_COMPOSE=$(curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
  - curl -L "https://github.com/docker/compose/releases/download/$(echo $GET_LATEST_DOCKER_COMPOSE)/docker-compose-$(uname -s)-$(uname -m)" -o $DOCKER_PATH/docker-compose
  - chmod +x $DOCKER_PATH/docker-compose
  - sudo chmod +x $DOCKER_PATH/docker-compose
  - docker compose version

# |- Set user passwords
chpasswd:
  list: |
    ${USERNAME}:${PASSWORD}
    root:${PASSWORD}
  expire: false

# |- Output final message when cloud-init has finished
final_message: "The system is finally up, after $UPTIME seconds"
